name: Build and Test Android App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        target: default

    - name: Start Emulator
      run: |
        nohup emulator @test -no-window -no-audio -no-boot-anim &
        adb wait-for-device
        adb shell input keyevent 82
      shell: bash

    - name: Wait for Emulator to Finish Booting
      run: |
        boot_completed=""
        until [[ "$boot_completed" =~ "1" ]]; do
          sleep 5
          boot_completed=$(adb -s emulator-5554 shell getprop sys.boot_completed 2>&1 &)
          echo "Waiting for emulator to boot..."
        done
      shell: bash

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease
      shell: bash

    - name: Terminate Emulator
      run: |
        emulator_pid=$(pgrep -f "emulator.*-avd")
        if [ -n "$emulator_pid" ]; then
          echo "Emulator running, killing..."
          adb -s emulator-5554 emu kill || true
        else
          echo "No emulator running."
        fi
      shell: bash

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk
